def battingStats():
	battingStatsTemplate=(
		'Year',
		'Age',
		'Team',
		'League',
		'Games Played or Pitched',
		'Plate Appearances',
		'At Bats',
		'Runs Scored/Allowed',
		'Hits/Hits Allowed',
		'2B',
		'3B',
		'HR',
		'RBI',
		'SB',
		'CS',
		'BB',
		'SO',
		'BA',
		'OBP',
		'SLG',
		'OPS',
		'OPX+',
		'TB',
		'GDP',
		'HBP',
		'SH',
		'IBB',
		'Pos',
		'Awards')
	return battingStatsTemplate

def pitchingStats():
	pitchingStatsTemplate=(
		'Year',
		'Age',
		'Team',
		'League',
		'Games Played',
		'Games Started',
		'Games Finished',
		'Complete Games',
		'Shutuots',
		'Saves',
		'Innings Pitched',
		'Hits/Hits Allowed',
		'Runs Scored/Allowed',
		'Earned Runs Allowed',
		'Home Runs Hit/Allowed',
		'Bases on Balls/Walks',
		'Intentional Bases on Balls',
		'Strikeouts',
		'Times Hit by a Pitch',
		'Balks',
		'Wild Pitches',
		'Batters Faced',
		'(BB + H)/IP',
		'9 x SO / IP')
	return pitchingStatsTemplate